#!/bin/sh
# File: /etc/hotplug.d/iface/99-wisp-notify

# Load config & lang
CONF="/etc/telegram.conf"
[ -f "$CONF" ] || CONF="$(dirname "$0")/telegram.conf"
[ -f "$CONF" ] || exit 0
. "$CONF"

LANG_DIR=${LANG_DIR:-"/etc/telegram_lang"}
[ -d "$(dirname "$0")/lang" ] && LANG_DIR="$(dirname "$0")/lang"
LANG_FILE="${LANG_DIR}/${LANG:-en}.sh"

[ -f "$LANG_FILE" ] && . "$LANG_FILE" || . "${LANG_DIR}/en.sh"

safe_format() {
    local template="$1"
    shift
    local escaped_template
    escaped_template=$(echo "$template" | sed 's/%/%%/g; s/%%s/%s/g')
    printf "$escaped_template" "$@"
}


if [ "$INTERFACE" = "wwan" ] || [ "$INTERFACE" = "wan" ]; then
    DOWN_TIME_FILE="/tmp/${INTERFACE}_down_time"

    if [ "$ACTION" = "ifdown" ]; then
        date +%s > "$DOWN_TIME_FILE"
    
    elif [ "$ACTION" = "ifup" ]; then
        IP=$(ifstatus "$INTERFACE" | jsonfilter -e '@["ipv4-address"][0].address' 2>/dev/null)
        [ -z "$IP" ] && IP="unknown"
        
        if [ "$INTERFACE" = "wwan" ]; then
            # WISP Mode
            WWAN_DEV=$(uci -q get network.wwan.device || echo "phy0-sta0")
            SIGNAL=$(iw dev "$WWAN_DEV" link 2>/dev/null | grep signal | awk '{print $2}')
            [ -z "$SIGNAL" ] && SIGNAL="unknown"

            if [ -f "$DOWN_TIME_FILE" ]; then
                DOWN_TIME=$(cat "$DOWN_TIME_FILE")
                UP_TIME=$(date +%s)
                DURATION=$((UP_TIME - DOWN_TIME))
                MINUTES=$((DURATION / 60))
                SECONDS=$((DURATION % 60))
                
                rm -f "$DOWN_TIME_FILE"
                
                MSG=$(safe_format "$MSG_WISP_RECOVER" "$MINUTES" "$SECONDS" "$IP" "$SIGNAL")
            else
                MSG=$(safe_format "$MSG_WISP_CONNECTED" "$IP" "$SIGNAL")
            fi
        else
            # Wired Mode
            if [ -f "$DOWN_TIME_FILE" ]; then
                DOWN_TIME=$(cat "$DOWN_TIME_FILE")
                UP_TIME=$(date +%s)
                DURATION=$((UP_TIME - DOWN_TIME))
                MINUTES=$((DURATION / 60))
                SECONDS=$((DURATION % 60))
                
                rm -f "$DOWN_TIME_FILE"
                
                MSG=$(safe_format "$MSG_WIRED_RECOVER" "$MINUTES" "$SECONDS" "$IP")
            else
                MSG=$(safe_format "$MSG_WIRED_CONNECTED" "$IP")
            fi
        fi

        /usr/bin/telegram_notify.sh "NETWORK" "$MSG"
    fi
fi

